const INITIAL_TOOLBOX_XML = '<xml>\n'
  + '  <category name="Lógica" colour="#3d9eff">\n'
  + '    <block type="controls_if"></block>\n'
  + '    <block type="logic_compare">\n'
  + '      <field name="OP">EQ</field>\n'
  + '    </block>\n'
  + '    <block type="logic_operation">\n'
  + '      <field name="OP">AND</field>\n'
  + '    </block>\n'
  + '    <block type="logic_negate"></block>\n'
  + '  </category>\n'
  + '  <category name="Laços" colour="#5CA65C">\n'
  + '    <block type="controls_whileUntil">\n'
  + '      <field name="MODE">WHILE</field>\n'
  + '    </block>\n'
  + '    <block type="controls_for">\n'
  + '      <field name="VAR" id="C(8;cYCF}~vSgkxzJ+{O" variabletype="">i</field>\n'
  + '      <value name="FROM">\n'
  + '        <shadow type="math_number">\n'
  + '          <field name="NUM">1</field>\n'
  + '        </shadow>\n'
  + '      </value>\n'
  + '      <value name="TO">\n'
  + '        <shadow type="math_number">\n'
  + '          <field name="NUM">10</field>\n'
  + '        </shadow>\n'
  + '      </value>\n'
  + '      <value name="BY">\n'
  + '        <shadow type="math_number">\n'
  + '          <field name="NUM">1</field>\n'
  + '        </shadow>\n'
  + '      </value>\n'
  + '    </block>\n'
  + '    <block type="controls_flow_statements">\n'
  + '      <field name="FLOW">BREAK</field>\n'
  + '    </block>\n'
  + '  </category>\n'
  + '  <category name="Matemática" colour="#5C68A6">\n'
  + '    <block type="math_number">\n'
  + '      <field name="NUM">0</field>\n'
  + '    </block>\n'
  + '    <block type="math_arithmetic">\n'
  + '      <field name="OP">ADD</field>\n'
  + '      <value name="A">\n'
  + '        <shadow type="math_number">\n'
  + '          <field name="NUM">1</field>\n'
  + '        </shadow>\n'
  + '      </value>\n'
  + '      <value name="B">\n'
  + '        <shadow type="math_number">\n'
  + '          <field name="NUM">1</field>\n'
  + '        </shadow>\n'
  + '      </value>\n'
  + '    </block>\n'
  + '    <block type="math_modulo">\n'
  + '      <value name="DIVIDEND">\n'
  + '        <shadow type="math_number">\n'
  + '          <field name="NUM">64</field>\n'
  + '        </shadow>\n'
  + '      </value>\n'
  + '      <value name="DIVISOR">\n'
  + '        <shadow type="math_number">\n'
  + '          <field name="NUM">10</field>\n'
  + '        </shadow>\n'
  + '      </value>\n'
  + '    </block>\n'
  + '  </category>\n'
  + '  <category name="Texto" colour="#5CA68D">\n'
  + '    <block type="text_print">\n'
  + '      <value name="TEXT">\n'
  + '        <shadow type="text">\n'
  + '          <field name="TEXT">abc</field>\n'
  + '        </shadow>\n'
  + '      </value>\n'
  + '    </block>\n'
  + '    <block type="text_prompt_text">\n'
  + '      <mutation type="TEXT"></mutation>\n'
  + '      <field name="TYPE">TEXT</field>\n'
  + '      <value name="TEXT">\n'
  + '        <shadow type="text">\n'
  + '          <field name="TEXT">abc</field>\n'
  + '        </shadow>\n'
  + '      </value>\n'
  + '    </block>\n'
  + '    <block type="text">\n'
  + '      <field name="TEXT"></field>\n'
  + '    </block>\n'
  + '  </category>\n'  + '  <sep></sep>\n'
  +'   <category name="Variáveis" colour="#9A5CA6" custom="CREATE_TYPED_VARIABLE"></category>'
  + '</xml>';

  export default INITIAL_TOOLBOX_XML;